#!/usr/bin/env python

from json import load
from os import listdir
from os.path import join
from re import compile

LOADING_DIR = 'loading'

AWS_LINK_RE = compile(r'<a href="http://www.amazon.com/exec/obidos/ASIN/(?P<asin>[^"]+)/krondonet-20">.*?</a>(?P<review>.*)')

GR_KEY = 'S7U07cOT8tvGRroS25BicQ'
GR_SECRET = 'KO2F81nBvsd2zLTCIdUfszHvccGCbPXmNXgl3k3jYw'

GR_ASIN_TO_ID_URL = 'https://www.goodreads.com/book/isbn_to_id'


class Book(object):

    def __init__(self, post):
        self._post = post
        match = AWS_LINK_RE.match(post['post_content'])
        self.asin = match.group('asin')
        self.review = match.group('review')

    def get_goodreads_id(self):
        response = get(GR_ASIN_TO_ID_URL,
                       params={'key': GR_KEY, 'isbn': self.asin})
        return response.text


def get_books():
    with open('wp_posts.json') as f:
        posts = load(f)

    return [
        Book(post) for post in posts
        if post['post_title'].startswith('Book:')
    ]


def main():
    book = get_books()[0]
    print book.asin, book.review, book.get_goodreads_id()


if __name__ == '__main__':
    main()
