#!/usr/bin/env python

from json import load
from os import listdir
from os.path import join

LOADING_DIR = 'loading'


def get_books():
    with open('wp_posts.json') as f:
        posts = load(f)

    return [post for post in posts if post['post_title'].startswith('Book:')]


def main():
    print get_books()[0]


if __name__ == '__main__':
    main()
