#!/usr/bin/env python

from json import load
from os import listdir
from os.path import join
from re import compile
from subprocess import PIPE
from subprocess import Popen
from tempfile import NamedTemporaryFile

from requests import get

LOADING_DIR = 'loading'

AWS_LINK_RE = compile(r'<a href="http://www.amazon.com/exec/obidos/ASIN/(?P<asin>[^"]+)/krondonet-20">.*?</a>(?P<review>.*)')

GR_KEY = 'S7U07cOT8tvGRroS25BicQ'
GR_SECRET = 'KO2F81nBvsd2zLTCIdUfszHvccGCbPXmNXgl3k3jYw'

GR_ASIN_TO_ID_URL = 'https://www.goodreads.com/book/isbn_to_id'
GR_CREATE_REVIEW_URL = 'https://www.goodreads.com/review.xml'


class Book(object):

    def __init__(self, post):
        self._post = post
        match = AWS_LINK_RE.match(post['post_content'])
        self.asin = match.group('asin')
        self.review = match.group('review')

    def get_goodreads_id(self):
        response = get(GR_ASIN_TO_ID_URL,
                       params={'key': GR_KEY, 'isbn': self.asin})
        return response.text

    def get_review_text(self):
        return html2text(self.review)

    def create_review(self):
        review = {
            'book_id': self.get_goodreads_id(),
            'review[read_at]': self._post['post_date'].split()[0],
            'review[review]': self.get_review_text(),
            'shelf': 'read',
        }


def html2text(html):
    with NamedTemporaryFile() as tempfile:
        tempfile.write(html)
        tempfile.flush()
        cmd = ['html2text', 'file:///{}'.format(tempfile.name)]
        p = Popen(cmd, stdout=PIPE)
        out, _ = p.communicate()
        assert p.returncode == 0
        return out


def get_books():
    with open('wp_posts.json') as f:
        posts = load(f)

    return [
        Book(post) for post in posts
        if post['post_title'].startswith('Book:')
    ]


def main():
    book = get_books()[0]
    import ipdb ; ipdb.set_trace()

    print book.asin, book.get_review_text(), book.get_goodreads_id()


if __name__ == '__main__':
    main()
